### ISSUE TITLE
How do you suggest handling existing pusher client?

### ISSUE THREAD

**Issue by mledom** [chrismccord/sync#106]
We have been using Pusher in other areas of our app. Since I have added sync I'm getting conflicts with Pusher. Sync is always creating a new Pusher client in the global scope and is wiping out the instance the rest of the app is using for authenticated messaging from the server. I could add some code that waits for Sync to connect but I was thinking it would be nice if the Faye and Pusher instantiations could check to see if the client already exists and is connected. If so use the existing client instead of creating a new one. What do you think?

**Comment by martikaljuve** [comment]
To use this with [Slanger](https://github.com/stevegraham/slanger), I copied the sync.coffee.erb file into my project and added a variable:

```diff
# app/assets/javascripts/sync.coffee.erb
    @Sync =
-    
+    client_instance: null

/../

  connect: ->
-    @client = new window.Pusher(Sync.PUSHER_API_KEY)
+    @client = Sync.client_instance || new window.Pusher(Sync.PUSHER_API_KEY)
```

And assigned it elsewhere like this:

```js
// app/assets/javascripts/application.js.erb
var pusher = new Pusher('my-api-key', {
    wsHost: 'api.example.com',
    enabledTransports: ['ws', 'flash']
});

Sync.client_instance = pusher;
```

I also wanted to use an existing Pusher client on the Ruby side, so I emptied [`Sync::Clients::Pusher::setup`](https://github.com/chrismccord/sync/blob/master/lib/sync/clients/pusher.rb) in an initializer:

````rb
# config/initializers/sync.rb
require 'sync'

module Sync
	module Clients
		class Pusher
			def setup
			end
		end
	end
end
```

Otherwise Sync replaces Pusher.app_id, Pusher.key and Push.secret with values from sync.yml.

**Comment by ajb** [comment]
For better or for worse, `Sync.Pusher` is exposed as a global. So you could do:

```js
Sync.Pusher.prototype.connect = function(){
  this.client = existingPusherClient;
}
```
