### ISSUE TITLE
sync_update @comment.parent - Doesn'nt work. Bug?

### ISSUE THREAD

**Issue by nadeemja** [chrismccord/sync#171]
Hi,

I've followed instructions 100%, and sync_update doesn't work.
Therefore, I believe it's a bug, and I'm posting here and not on StackOverflow.

I'm using this them:
https://github.com/elight/acts_as_commentable_with_threading

And, heres my code:

Controller:
 
    def show
      @comments = @question.root_comments
    end

    def create
        @comment = Comment.new(comment_params)
        @comment.user_id = current_user.id
        @comment.commentable_type = 'Question'
        if @comment.save
          if @comment.parent == nil
            sync_new @comment, scope: [@comment.commentable, :root]
          else
            sync_new @comment, scope: [@comment.parent, :child]
            sync_update @comment.parent
          end

        end
    end

show.html.haml

     %ul.gNow
      - @comments.each do |comment|
        = sync partial: 'comment', resource: comment

      = sync_new partial: 'comment', resource: Comment.new, scope: [@question, :root]

sync/comments/_comment.html.haml

    .row
      %div{class: "col-xs-#{12 - comment.depth} col-xs-offset-#{comment.depth} pull-right"}
        %li
          .card
            .pull-left
              %small{style: 'margin-right:5px;'}
                #{comment.user.identity}: 
              
            .pull-right
              %small{style: 'margin-right:5px;'}
                = link_to "Reply (#{comment.children.count})", '#', comment_id: "comment-#{comment.id}", class: 'show-comments', remote: true
              
            %p        
              = comment.body
            
    %div{class: "row comment-#{comment.id} hidden"}
      .col-md-12
        - if comment.has_children?
          - comment.children.each do |child|
            = sync partial: 'comment', resource: child

        = sync_new partial: 'comment', resource: Comment.new, scope: [comment, :child]

    %div{class: "row comment-#{comment.id} hidden"}
      %div{class: "col-xs-#{12 - comment.depth - 1} col-xs-offset-#{comment.depth + 1} pull-right"}

        %li
          .card
            %p
              = render partial: 'comments/form', locals: {c: comment, question: comment.commentable}

The problem is that the comment.children.count doesn't update in the view. None of the other attributes update either.

Please advise :)

**Comment by ajb** [comment]
What was the issue?

**Comment by nadeemja** [comment]
Well, it worked when I used refetch: true, even though I don't understand why this would be neccessary. Anyways, "refetch: true" screws with all my binds on the Reply-link. The links all stop working after another comment is added.

Also, refetching caused some weird behavior, like duplicates of parent and child comments being added to DOM whenever another comment was added. Refreshing the page cleared the duplicates.

**Comment by ajb** [comment]
If you can either add a failing test to `sync` or provide an isolated test case, I'd be happy to investigate further, otherwise I'm not sure I can be of much help. Glad to hear you found a workaround, it sounds like.

**Comment by mgomes** [comment]
This is the type of use case I had which led me to add in the explicit partial syncing (more info: https://github.com/chrismccord/sync#scoping-by-partial). 

The problem here is that when a child comment is being added, you are updating the parent which is causing the entire parent container to be re-rendered and taking all of the children comments along with it. Unless you are binding your JS to `document` this would break your JS bindings as well. 

If all you want to do is update the count, then I'd suggest creating a separate tiny partial for that called `comment_count` that only renders the count. That way instead of calling `sync_update @comment.parent` in your controller,  you would call, `sync_update @comment.parent, partial: 'comment_count', scope: [@comment.parent, :comment_count]` or something like it.
