### ISSUE TITLE
Duplicate Partials Fail to Update

### ISSUE THREAD

**Issue by mgomes** [chrismccord/sync#180]
I have a page that has two of the same partials rendered. Upon first update, both update accordingly. After the second and subsequent updates however, both partials fail to update.

The workaround would be for me to change the names of each partial and duplicate the code across both, but it would be nice if this were supported.

I'd be happy to submit a PR. Can anyone give me some hints as to why this is happening or if this would be a big change?

**Comment by chrismccord** [comment]
Have you looked at the "caveats" section of the readme? Likely you just need to place your partial in a toplevel tag.

**Comment by mgomes** [comment]
It's a pretty simple partial wrapped in a span:

```erb
<span class="user_score"><%= user.score %></span>
```

It works well when only one of them are rendered on a page. The issue is that the score is rendered in the nav bar and in the user's profile page. So when one is viewing their own profile, they are seeing two of those partials on the page.

**Comment by ajb** [comment]
You might want to take a look at https://github.com/chrismccord/sync/blob/6ff1f7e5a167947daf8be46b5f3cee21e2d038b9/app/assets/javascripts/sync.coffee.erb#L186

I would suspect that only one message is being sent to the client, which results in only one new DOM node being created. We would need to modify the update handler to use `$.clone()` in order to replace both of your `.user_score`s with the received HTML.

Does that make sene?

**Comment by mgomes** [comment]
That makes sense. I'll take a stab at it. Thanks.

**Comment by ajb** [comment]
Moving discussion to #181
