### ISSUE TITLE
Google recognising IDs in generated JavaScript as URLs

### ISSUE THREAD

**Issue by henare** [chrismccord/sync#198]
Thank you for this Gem! We use it on morph.io and noticed that Google Webmaster Tools was finding a lot of URLs it couldn't crawl: https://github.com/openaustralia/morph/issues/745

It turns out that because of the preceeding `/` in things like the `authToken` in the generated JavaScript, Google thinks they might be URLs so it tries to crawl them. Is it feasible to change this (maybe just removing the leading `/`)?

If the answer is no it's not a major problem (it doesn't impact your site's ranking) and I'll happily contribute a note to the README so it doesn't confuse other people.

**Comment by ajb** [comment]
Hey @henare, thanks for opening the issue. It looks like Faye requires channel names to start with the `/`: http://faye.jcoglan.com/browser/subscribing.html

Here's where we're generating the channel name in our lib. I didn't write that code, but it looks pretty deliberate: https://github.com/chrismccord/sync/blob/6ff1f7e5a167947daf8be46b5f3cee21e2d038b9/lib/sync/clients/faye.rb#L24

We could try appending the `/` via javascript, instead of adding it to the `data-*` attribute? But it seems like a lot of work for something that [you can safely ignore](https://support.google.com/webmasters/answer/2409439?ctx=MCE&ctx=NF).

**Comment by henare** [comment]
>But it seems like a lot of work for something that you can safely ignore.

I totally agree.

I've opened a pull request to add a note to the README so other people aren't tripped up by this.
